
import Head from "next/head";
import useSWR from 'swr';
import styles from "@/styles/Home.module.css";
import Image from 'next/image'

export default function Home() {
  const fetcher = (url) => fetch(url).then((res) => res.json());
  const { data } = useSWR('/api/paintings', fetcher);

  return (
    <>
      <Head>
        <title>Paint and Sip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>1.5 Gen Asians Meetup - Paint & Sip</h1>
        {!data && "Loading..."}
        {data && Object.entries(data).map(([key, value], i) => {
          return (
            <div className={`${styles.section}`}>
              <h2>{key}</h2>
              {
                value && value.map(imgPath => <img src={imgPath} alt="" />)
              }
            </div>
          )
        })}
      </main>
    </>
  );
}
