
import Head from "next/head";
import useSWR from 'swr';
import styles from "@/styles/Home.module.css";
import Painting from "@/components/Painting";

export default function Home() {
  const fetcher = (url) => fetch(url).then((res) => res.json());
  const { data } = useSWR('/api/paintings', fetcher);
  const { data: votes } = useSWR('/api/selection', fetcher);

  return (
    <>
      <Head>
        <title>Paint and Sip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>1.5 Gen Asians Meetup - Paint & Sip</h1>
        <section>
          <h2>The Current Top Two Selections Are</h2>
          {!votes && "Loading votes..."}
          {votes && votes.votes.map(vote => {
            return (
              <img key={vote.name + vote.vote} width="240" src={vote.name} style={{ margin: "5px", border: "10px solid white" }} />)
          })}
        </section>
        <section>
          {!data && "Loading paintings..."}
          {data && Object.entries(data).map(([key, value], i) => {
            return (
              <div className={`${styles.section}`}>
                <h2>{key}</h2>
                {
                  value && value.map(imgPath => <Painting key={imgPath} imgPath={imgPath} />)
                }
              </div>
            )
          })}
        </section>
      </main>
    </>
  );
}
